# Generated by Django 3.1.5 on 2021-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, default='Cart', max_length=256),
        ),
    ]
